In [2]:
import numpy as np

In [3]:
a=np.array(90)
print(a)

90


In [4]:
a=np.array(0)
a.ndim

0

In [5]:
b=np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [6]:
b=np.array([1,2,3,4,5])
b.ndim

1

In [7]:
c=np.array([["Ali","Ahmad","King"],["A","B","C"]])
c

array([['Ali', 'Ahmad', 'King'],
       ['A', 'B', 'C']], dtype='<U5')

In [8]:
c.ndim

2

In [9]:
c=np.array([[["Ali","Ahmad","King"]],[["A","B","C"]]] )
c.ndim

3

In [10]:
b=np.array([1,2,3,4,5])
b[1:5]

array([2, 3, 4, 5])

In [11]:
b=np.array([1,2,3,4,5])
b[-3:-1]

array([3, 4])

In [12]:
c=np.array([["Ali","Ahmad","King"],["A","B","C"]])
for i in np.nditer(c):
    print(i)

Ali
Ahmad
King
A
B
C


In [13]:
r=np.array([5,6,7,8,9])
for i,j in np.ndenumerate(r):
    print(i,j)

(0,) 5
(1,) 6
(2,) 7
(3,) 8
(4,) 9


In [14]:
a=np.array([2,3,4,5])
b=np.array([22,34,42,125])
c=np.concatenate((a,b))
c

array([  2,   3,   4,   5,  22,  34,  42, 125])

In [15]:
a=np.array([2,3,4,5])
b=np.array([22,34,42,125])
c=np.stack((a,b))
c

array([[  2,   3,   4,   5],
       [ 22,  34,  42, 125]])

In [16]:
a=np.array([2,3,4,5,67])
b=np.array([22,34,42,125,77])
c=np.dstack((a,b))
c

array([[[  2,  22],
        [  3,  34],
        [  4,  42],
        [  5, 125],
        [ 67,  77]]])

In [17]:
a=np.array([2,3,4,5,6,7])
np.array_split(a,3)

[array([2, 3]), array([4, 5]), array([6, 7])]

In [18]:
a=np.array([872,223,4,5,6,7])
np.sort(a)

array([  4,   5,   6,   7, 223, 872])

In [19]:
a=np.array([4,5,6,7])
k=np.searchsorted(a,6)
k

2

In [20]:
a=np.array([872,223,4,5,6,7])
i=np.where(a==4)
i

(array([2], dtype=int64),)

In [1]:
import random
a=random.randint(130,200)
a

200